const fs = require('fs');
const file = 'backend/src/db/seeds/seed.ts';
let content = fs.readFileSync(file, 'utf8');

const newData = `const demoSubscribersData = [
  { accountNumber: 'BCIS-SUB-2026-0001', firstName: 'Juan', middleName: 'Bautista', lastName: 'Mercado', businessName: null, primaryContactNumber: '0917-555-0101', secondaryContactNumber: '088-813-1101', email: 'juan.mercado@gmail.com', status: 'ACTIVE', notes: 'Residential fiber subscriber since January 2026.', address: { label: 'Home', line1: 'Purok 3, Sayre Highway', line2: 'Near Casisang Central School', barangay: 'Casisang', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: 'Yellow 2-storey house with black gate' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0001', serviceTypeCode: 'INTERNET', servicePlanCode: 'PLAN-INT-50M', activationDate: '2026-01-15', billingStartDate: '2026-01-15', billingDay: 1, dueDay: 15, currentRate: '1299.00', status: 'ACTIVE', collectorCode: 'COL-001', collectionAreaCode: 'AREA-CAS', cachedBalanceDue: '0.00' } },
  { accountNumber: 'BCIS-SUB-2026-0002', firstName: 'Maria Clara', middleName: 'Santos', lastName: 'Garcia', businessName: 'Garcia Mini Mart', primaryContactNumber: '0920-555-0202', secondaryContactNumber: null, email: 'mc.garcia@yahoo.com', status: 'ACTIVE', notes: 'Commercial combo internet and cable subscriber.', address: { label: 'Business Store', line1: 'Fortich Street, Corner San Isidro', line2: 'Building B, Ground Floor', barangay: 'Poblacion', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: 'Opposite City Hall Plaza' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0002', serviceTypeCode: 'COMBO', servicePlanCode: 'PLAN-COM-30M', activationDate: '2026-02-01', billingStartDate: '2026-02-01', billingDay: 1, dueDay: 15, currentRate: '1299.00', status: 'ACTIVE', collectorCode: 'COL-002', collectionAreaCode: 'AREA-POB', cachedBalanceDue: '0.00' } },
  { accountNumber: 'BCIS-SUB-2026-0003', firstName: 'Roberto', middleName: 'Sy', lastName: 'Tan', businessName: null, primaryContactNumber: '0908-555-0303', secondaryContactNumber: null, email: 'robert.tan@outlook.com', status: 'ACTIVE', notes: 'Cable television subscriber. Currently suspended due to unpaid bill.', address: { label: 'Home', line1: 'Purok 5, Zone 2', line2: 'Block 4 Lot 12', barangay: 'Sumpong', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: 'Behind Sumpong Barangay Hall' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0003', serviceTypeCode: 'CABLE', servicePlanCode: 'PLAN-CAB-STD', activationDate: '2025-11-10', billingStartDate: '2025-11-10', billingDay: 1, dueDay: 15, currentRate: '499.00', status: 'SUSPENDED', collectorCode: 'COL-001', collectionAreaCode: 'AREA-SMP', cachedBalanceDue: '1497.00', statusHistoryReason: 'Non-payment of past due invoices' } },
  { accountNumber: 'BCIS-SUB-2026-0004', firstName: 'Ferdinand', middleName: 'Reyes', lastName: 'Cruz', businessName: null, primaryContactNumber: '0919-555-0404', secondaryContactNumber: null, email: 'fred.cruz@gmail.com', status: 'ACTIVE', notes: 'Long-term subscriber.', address: { label: 'Home', line1: 'Subdivision Road 1', line2: '', barangay: 'Kalasungay', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: 'Red gate' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0004', serviceTypeCode: 'INTERNET', servicePlanCode: 'PLAN-INT-100M', activationDate: '2024-05-12', billingStartDate: '2024-05-12', billingDay: 1, dueDay: 15, currentRate: '1699.00', status: 'ACTIVE', collectorCode: 'COL-001', collectionAreaCode: 'AREA-CAS', cachedBalanceDue: '0.00' } },
  { accountNumber: 'BCIS-SUB-2026-0005', firstName: 'Corazon', middleName: 'Alcantara', lastName: 'Dela Rosa', businessName: 'Cora Beauty Salon', primaryContactNumber: '0922-555-0505', secondaryContactNumber: null, email: 'cora.delarosa@yahoo.com', status: 'ACTIVE', notes: '', address: { label: 'Shop', line1: 'Market Site', line2: 'Stall 45', barangay: 'Poblacion', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: 'Near fish section' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0005', serviceTypeCode: 'COMBO', servicePlanCode: 'PLAN-COM-60M', activationDate: '2023-11-01', billingStartDate: '2023-11-01', billingDay: 1, dueDay: 15, currentRate: '1699.00', status: 'ACTIVE', collectorCode: 'COL-002', collectionAreaCode: 'AREA-POB', cachedBalanceDue: '1699.00' } },
  { accountNumber: 'BCIS-SUB-2026-0006', firstName: 'Arturo', middleName: 'V.', lastName: 'Panganiban', businessName: null, primaryContactNumber: '0933-555-0606', secondaryContactNumber: null, email: 'art.panganiban@gmail.com', status: 'ACTIVE', notes: '', address: { label: 'Home', line1: 'Purok 1', line2: '', barangay: 'Sumpong', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: '' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0006', serviceTypeCode: 'CABLE', servicePlanCode: 'PLAN-CAB-PREM', activationDate: '2026-03-01', billingStartDate: '2026-03-01', billingDay: 1, dueDay: 15, currentRate: '799.00', status: 'ACTIVE', collectorCode: 'COL-001', collectionAreaCode: 'AREA-SMP', cachedBalanceDue: '0.00' } },
  { accountNumber: 'BCIS-SUB-2026-0007', firstName: 'Lourdes', middleName: 'M.', lastName: 'Navarro', businessName: 'Navarro Eatery', primaryContactNumber: '0944-555-0707', secondaryContactNumber: null, email: 'lourdes.navarro@gmail.com', status: 'ACTIVE', notes: '', address: { label: 'Restaurant', line1: 'Highway', line2: '', barangay: 'Casisang', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: '' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0007', serviceTypeCode: 'INTERNET', servicePlanCode: 'PLAN-INT-50M', activationDate: '2025-08-20', billingStartDate: '2025-08-20', billingDay: 1, dueDay: 15, currentRate: '1299.00', status: 'ACTIVE', collectorCode: 'COL-001', collectionAreaCode: 'AREA-CAS', cachedBalanceDue: '2598.00' } },
  { accountNumber: 'BCIS-SUB-2026-0008', firstName: 'Jose', middleName: 'Rizal', lastName: 'Mendoza', businessName: null, primaryContactNumber: '0955-555-0808', secondaryContactNumber: null, email: 'jose.mendoza@gmail.com', status: 'ACTIVE', notes: '', address: { label: 'Home', line1: 'Phase 2', line2: 'Block 8', barangay: 'Poblacion', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: '' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0008', serviceTypeCode: 'CABLE', servicePlanCode: 'PLAN-CAB-STD', activationDate: '2026-04-10', billingStartDate: '2026-04-10', billingDay: 1, dueDay: 15, currentRate: '499.00', status: 'ACTIVE', collectorCode: 'COL-002', collectionAreaCode: 'AREA-POB', cachedBalanceDue: '0.00' } },
  { accountNumber: 'BCIS-SUB-2026-0009', firstName: 'Carmela', middleName: 'P.', lastName: 'Rosales', businessName: null, primaryContactNumber: '0966-555-0909', secondaryContactNumber: null, email: 'carmela.rosales@yahoo.com', status: 'ACTIVE', notes: '', address: { label: 'Home', line1: 'Purok 4', line2: '', barangay: 'Sumpong', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: '' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0009', serviceTypeCode: 'INTERNET', servicePlanCode: 'PLAN-INT-25M', activationDate: '2026-01-05', billingStartDate: '2026-01-05', billingDay: 1, dueDay: 15, currentRate: '999.00', status: 'ACTIVE', collectorCode: 'COL-001', collectionAreaCode: 'AREA-SMP', cachedBalanceDue: '999.00' } },
  { accountNumber: 'BCIS-SUB-2026-0010', firstName: 'Eduardo', middleName: 'L.', lastName: 'Villanueva', businessName: 'Ed Auto Repair', primaryContactNumber: '0977-555-1010', secondaryContactNumber: null, email: 'ed.auto@gmail.com', status: 'ACTIVE', notes: '', address: { label: 'Shop', line1: 'National Highway', line2: '', barangay: 'Casisang', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: '' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0010', serviceTypeCode: 'COMBO', servicePlanCode: 'PLAN-COM-100M', activationDate: '2025-02-14', billingStartDate: '2025-02-14', billingDay: 1, dueDay: 15, currentRate: '2199.00', status: 'SUSPENDED', collectorCode: 'COL-001', collectionAreaCode: 'AREA-CAS', cachedBalanceDue: '6597.00', statusHistoryReason: 'Overdue accounts for 3 months' } },
  { accountNumber: 'BCIS-SUB-2026-0011', firstName: 'Ricardo', middleName: 'T.', lastName: 'Dalisay', businessName: null, primaryContactNumber: '0988-555-1111', secondaryContactNumber: null, email: 'cardo.d@gmail.com', status: 'ACTIVE', notes: '', address: { label: 'Home', line1: 'Purok 2', line2: '', barangay: 'Poblacion', cityMunicipality: 'Malaybalay City', province: 'Bukidnon', postalCode: '8700', landmark: '' }, serviceAccount: { serviceAccountNumber: 'BCIS-SA-2026-0011', serviceTypeCode: 'INTERNET', servicePlanCode: 'PLAN-INT-100M', activationDate: '2024-09-01', billingStartDate: '2024-09-01', billingDay: 1, dueDay: 15, currentRate: '1699.00', status: 'ACTIVE', collectorCode: 'COL-002', collectionAreaCode: 'AREA-POB', cachedBalanceDue: '0.00' } }
];`;

const startIdx = content.indexOf('const demoSubscribersData = [');
const endIdx = content.indexOf('];\n\n  for (const s of demoSubscribersData)', startIdx);

if (startIdx !== -1 && endIdx !== -1) {
  content = content.substring(0, startIdx) + newData + content.substring(endIdx + 2);
  fs.writeFileSync(file, content, 'utf8');
  console.log('Seed file updated successfully.');
} else {
  console.log('Could not find demoSubscribersData block.');
  // fallback search
  const alternativeEnd = content.indexOf('];', startIdx);
  if (alternativeEnd !== -1) {
    content = content.substring(0, startIdx) + newData + content.substring(alternativeEnd + 2);
    fs.writeFileSync(file, content, 'utf8');
    console.log('Seed file updated successfully (fallback).');
  }
}
